// ─────────────────────────────────────────────────────────────
// Common
// ─────────────────────────────────────────────────────────────

export interface PaginationQuery {
  page?: number;
  limit?: number;
}

export interface PaginatedResult<T> {
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

// ─────────────────────────────────────────────────────────────
// Auto Mech Vendor
// ─────────────────────────────────────────────────────────────

export type VendorStatus = 'pending' | 'approved' | 'rejected' | 'suspended' | 'inactive';

export interface AutoMechVendor {
  id: string;
  userId: string;
  businessName: string;
  description: string | null;
  phone: string;
  email: string | null;
  address: string;
  city: string;
  state: string;
  latitude: number;
  longitude: number;
  coverImageUrl: string | null;
  logoUrl: string | null;
  status: VendorStatus;
  rating: number;
  totalCustomers: number;
  totalHoursServed: number;
  operatingHours: OperatingHours;
  isOpenNow?: boolean;
  distanceKm?: number;
  createdAt: string;
  updatedAt: string;
}

export interface OperatingDay {
  open: string;   // e.g. "08:00"
  close: string;  // e.g. "19:00"
  closed: boolean;
}

export interface OperatingHours {
  monday: OperatingDay;
  tuesday: OperatingDay;
  wednesday: OperatingDay;
  thursday: OperatingDay;
  friday: OperatingDay;
  saturday: OperatingDay;
  sunday: OperatingDay;
}

// ─────────────────────────────────────────────────────────────
// Auto Mech Service / Package
// ─────────────────────────────────────────────────────────────

export type MechCategory =
  | 'oil_change'
  | 'tyre_service'
  | 'brake_service'
  | 'engine_repair'
  | 'electrical_repair'
  | 'general_service';

export interface AutoMechService {
  id: string;
  vendorId: string;
  name: string;
  description: string | null;
  category: MechCategory | null;
  customCategoryId: string | null;
  durationMinutes: number;
  price: number;
  priceMin: number | null;   // lower bound for range pricing — mirrors price when set
  priceMax: number | null;   // upper bound — null means fixed price; shows "₦X - ₦Y" when set
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────
// Auto Mech Booking
// ─────────────────────────────────────────────────────────────

export type BookingType = 'book_now' | 'scheduled';
export type BookingStatus =
  | 'pending'
  | 'confirmed'
  | 'in_progress'
  | 'completed'
  | 'cancelled'
  | 'no_show';
export type PaymentMethod = 'wallet' | 'card' | 'cash';
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded';

export interface AutoMechBooking {
  id: string;
  bookingReference: string | null; // e.g. MEC-2024-001234 — auto-generated by DB trigger
  customerId: string;
  vendorId: string;
  serviceId: string;
  bookingType: BookingType;
  status: BookingStatus;
  scheduledAt: string | null;
  serviceAddress: string;
  serviceLatitude: number;
  serviceLongitude: number;
  // Vehicle structured fields
  vehicleMake: string | null;
  vehicleModel: string | null;
  vehicleYear: number | null;
  vehiclePlateNumber: string | null;
  vehicleDescription: string | null;  // free-text additional notes
  vehiclePhotoUrls: string[];
  notes: string | null;
  totalAmount: number;
  estimatedCostMin: number | null;    // lower cost bound stored at booking time
  estimatedCostMax: number | null;    // upper cost bound — null = fixed price
  durationDisplay: string | null;     // e.g. "60-180 minutes"
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  cancellationReason: string | null;
  cancelledAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  customerRating: number | null;
  customerFeedback: string | null;
  vendorRating: number | null;
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────
// Availability Slots
// ─────────────────────────────────────────────────────────────

export interface TimeSlot {
  time: string;        // "HH:MM" 24-hour
  displayTime: string; // "12:30 PM"
  available: boolean;
}

export interface DayAvailability {
  date: string;        // "YYYY-MM-DD"
  displayDate: string; // "Friday, August 14"
  slots: TimeSlot[];
}

// ─────────────────────────────────────────────────────────────
// Review / Rating
// ─────────────────────────────────────────────────────────────

export interface AutoMechReview {
  id: string;
  bookingId: string;
  customerId: string;
  vendorId: string;
  rating: number;
  comment: string | null;
  customerName: string;
  createdAt: string;
}

// ─────────────────────────────────────────────────────────────
// Vendor DTOs
// ─────────────────────────────────────────────────────────────

export interface CreateVendorDto {
  businessName: string;
  description?: string;
  phone: string;
  email?: string;
  address: string;
  city: string;
  state: string;
  latitude: number;
  longitude: number;
  operatingHours?: Partial<OperatingHours>;
}

export interface UpdateVendorDto {
  businessName?: string;
  description?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  latitude?: number;
  longitude?: number;
  operatingHours?: Partial<OperatingHours>;
}

// ─────────────────────────────────────────────────────────────
// Service / Package DTOs
// ─────────────────────────────────────────────────────────────

export interface CreateAutoMechServiceDto {
  name: string;
  description?: string;
  category?: MechCategory;
  customCategoryId?: string | null;
  durationMinutes: number;
  price: number;        // base / min price
  priceMin?: number;   // explicitly set lower bound (defaults to price)
  priceMax?: number;   // upper bound — omit for fixed pricing
}

export interface UpdateAutoMechServiceDto {
  name?: string;
  description?: string;
  category?: MechCategory;
  customCategoryId?: string | null;
  durationMinutes?: number;
  price?: number;
  priceMin?: number;
  priceMax?: number | null; // pass null to clear the upper bound (revert to fixed)
  isActive?: boolean;
}

// ─────────────────────────────────────────────────────────────
// Booking DTOs
// ─────────────────────────────────────────────────────────────

export interface CreateBookingDto {
  vendorId: string;
  serviceId: string;
  bookingType: BookingType;
  scheduledAt?: string;  // ISO date string, required when bookingType = 'scheduled'
  serviceAddress: string;
  serviceLatitude: number;
  serviceLongitude: number;
  // Vehicle structured fields — map to separate columns
  vehicleMake?: string;
  vehicleModel?: string;
  vehicleYear?: number;
  vehiclePlateNumber?: string;
  vehicleDescription?: string; // free-text / additional notes
  notes?: string;
  paymentMethod: PaymentMethod;
}

export interface UpdateBookingStatusDto {
  status: BookingStatus;
  cancellationReason?: string;
}

// ─────────────────────────────────────────────────────────────
// Search / Discovery
// ─────────────────────────────────────────────────────────────

export interface SearchVendorsQuery extends PaginationQuery {
  latitude: number;
  longitude: number;
  radiusKm?: number;
  category?: MechCategory;
  query?: string;
}

export type SortVendorsBy = 'distance' | 'rating' | 'newest';
